backend:
  name: git-gateway
  branch: main # Change to 'master' if your default branch is master

# Only enable local development when running locally
# local_backend: true

# Media files
media_folder: "public/portfolio"
public_folder: "/portfolio"

# Site configuration
site_url: https://your-portfolio-site.netlify.app # Update this when deployed
display_url: https://your-portfolio-site.netlify.app

# Collections
collections:
  # Simple Portfolio Configuration
  - name: "settings"
    label: "🎮 Portfolio Manager"
    files:
      - label: "Portfolio Projects"
        name: "portfolio-config"
        file: "public/portfolio-config.json"
        format: "json"
        fields:
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number", default: 1 }
              - { label: "Project Name", name: "projectName", widget: "string", hint: "e.g., Space Adventure" }
              - { label: "Project Description", name: "projectDescription", widget: "string", hint: "Brief description" }
              - label: "Project Color"
                name: "projectColor"
                widget: "select"
                options:
                  - { label: "Green", value: "primary" }
                  - { label: "Orange", value: "secondary" }
                  - { label: "Purple", value: "accent" }
                default: "primary"
              - label: "Artwork Items"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string", hint: "e.g., DRAGON BOSS" }
                  - label: "Category"
                    name: "category"
                    widget: "select"
                    options: ["ANIMATION", "CHARACTER", "OBJECTS", "UI", "ENVIRONMENT"]
                    default: "CHARACTER"
                  - { label: "Description", name: "description", widget: "text", hint: "Describe your artwork" }
                  - { label: "Image Path", name: "imagePath", widget: "string", hint: "e.g., my_project/image.png" }
                  - label: "Tags"
                    name: "tags"
                    widget: "list"
                    default: ["PIXEL", "ART"]
                    hint: "Add descriptive tags"

# Editor settings
editor:
  preview: true

# Logo
logo_url: /favicon.ico
